import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ResponsiveContainer, AreaChart, Area, LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell, ScatterChart, Scatter, ZAxis} from 'recharts';

const D = window.DASHBOARD_DATA || window.DASHBOARD_SAMPLE_DATA;
const COLORS = ['#118DFF','#12239E','#E66C37','#6B007B','#1AAB40','#D9B300','#D64554','#197278'];
const tabs = [
  ['performance','Desempenho comercial'], ['clientes','Análise de clientes'], ['churn','Churn'], ['rfv','RFV'], ['segmentos','Segmentos']
];
const money = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:Math.abs(n)>=1e6?'compact':'standard',maximumFractionDigits:1}).format(n||0);
const fullMoney = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n||0);
const pct = n => `${((n||0)*100).toFixed(1).replace('.',',')}%`;
const sum = (rows,key) => rows.reduce((a,b)=>a+(Number(b[key])||0),0);
const compact = n => new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(n||0);
const aggregate = (rows, key) => Object.values(rows.reduce((acc,row)=>{const k=row[key]||'Sem informação'; const item=acc[k]||(acc[k]={[key]:k,faturamento:0,margem:0,linhas:0,clientes:0}); item.faturamento+=Number(row.faturamento)||0; item.margem+=Number(row.margem)||0; item.linhas+=Number(row.linhas)||0; item.clientes+=1; return acc;},{}));
const EndLabel = ({x,y,value,index,total,kind='money'}) => (index===0||index===total-1) ? <text x={x} y={y-10} textAnchor="middle" fill="#605E5C" fontSize="10">{kind==='money'?money(value):`${Number(value).toFixed(1)}%`}</text> : null;
function Card({title,caption,children,className=''}){return <section className={`card ${className}`}><h3>{title}</h3>{caption&&<p className="caption">{caption}</p>}{children}</section>}
function Kpi({label,value,hint,tone=''}){return <div className={`kpi ${tone}`}><div className="label">{label}</div><div className="value">{value}</div><div className="hint">{hint}</div></div>}
function Table({rows,cols}){if(!rows.length)return <div className="empty">Nenhum registro para os filtros selecionados.</div>;return <div style={{overflowX:'auto'}}><table><thead><tr>{cols.map(c=><th key={c.label} className={c.num?'num':''}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.cliente||row.produto||row.periodo||i}>{cols.map(c=><td key={c.label} className={c.num?'num':''}>{c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table></div>}
function TooltipBox({active,payload,label}){if(!active||!payload?.length)return null;return <div style={{background:'#fff',border:'1px solid #C8C6C4',borderRadius:8,padding:10}}><b>{label}</b>{payload.map(p=><div key={p.name} style={{color:p.color}}>{p.name}: {p.name.includes('Margem')?pct(p.value/100):money(p.value)}</div>)}</div>}

function App(){
  const [page,setPage]=useState('performance'); const [business,setBusiness]=useState('Todos'); const [from,setFrom]=useState(D.meta.periodoInicial); const [to,setTo]=useState(D.meta.periodoFinal); const [customerFilter,setCustomerFilter]=useState('Todos');
  const periods = useMemo(()=>[...new Set(D.monthly.map(x=>x.periodo))].sort(),[]);
  const scopedMonthly = useMemo(()=>D.monthly.filter(x=>(business==='Todos'||x.business===business)&&x.periodo>=from&&x.periodo<=to),[business,from,to]);
  const scopedProducts = useMemo(()=>D.products.filter(x=>(business==='Todos'||x.business===business)&&x.periodo>=from&&x.periodo<=to),[business,from,to]);
  const scopedCustomers = useMemo(()=>D.customers.filter(x=>business==='Todos'||x.business===business),[business]);
  const visibleCustomers = useMemo(()=>customerFilter==='Todos'?scopedCustomers:scopedCustomers.filter(x=>x.grupo_cliente===customerFilter||x.grupo_rfv===customerFilter||x.churn===customerFilter),[scopedCustomers,customerFilter]);
  const monthly = useMemo(()=>aggregate(scopedMonthly,'periodo').map(x=>({...x,margemPct:x.faturamento?x.margem/x.faturamento:0})).sort((a,b)=>a.periodo.localeCompare(b.periodo)),[scopedMonthly]);
  const topProducts = useMemo(()=>aggregate(scopedProducts,'produto').sort((a,b)=>b.faturamento-a.faturamento).slice(0,10),[scopedProducts]);
  const totalRevenue=sum(scopedMonthly,'faturamento'), totalMargin=sum(scopedMonthly,'margem');
  const customerGroups=useMemo(()=>aggregate(visibleCustomers,'grupo_cliente').sort((a,b)=>b.faturamento-a.faturamento),[visibleCustomers]);
  const churn=useMemo(()=>aggregate(visibleCustomers,'churn').sort((a,b)=>b.faturamento-a.faturamento),[visibleCustomers]);
  const rfv=useMemo(()=>aggregate(visibleCustomers,'grupo_rfv').sort((a,b)=>b.faturamento-a.faturamento),[visibleCustomers]);
  const clusters=useMemo(()=>aggregate(visibleCustomers,'cluster').map(x=>({...x,cluster:`Cluster ${x.cluster}`})).sort((a,b)=>b.faturamento-a.faturamento),[visibleCustomers]);
  const opportunities=useMemo(()=>[...visibleCustomers].filter(x=>x.variacao_2025<0&&x.margem>0).sort((a,b)=>a.variacao_2025-b.variacao_2025).slice(0,10),[visibleCustomers]);
  const latestMargin=monthly.at(-1)?.margemPct||0; const earliestMargin=monthly[0]?.margemPct||0;
  const setWindow = months=>{const end=periods.at(-1);setTo(end);setFrom(periods[Math.max(0,periods.length-months)]);};
  const groups=['Todos',...new Set([...scopedCustomers.map(x=>x.grupo_cliente),...scopedCustomers.map(x=>x.grupo_rfv),...scopedCustomers.map(x=>x.churn)])].sort();
  const pageTitle={performance:['Desempenho comercial','Acompanhe vendas, faturamento líquido e evolução de margem.'],clientes:['Análise de clientes','Priorize carteira, oportunidades de recuperação e desenvolvimento de mix.'],churn:['Churn observado','Trate inatividade como sinal de ação, não como cancelamento confirmado.'],rfv:['Análise RFV','Recência, frequência e valor organizam a prioridade comercial.'],segmentos:['Segmentos da carteira','Grupos de comportamento ajudam a adaptar cobertura e negociação.']}[page];
  const insights=[
    `Margem no último período selecionado: ${pct(latestMargin)} ${latestMargin>=earliestMargin?'— acima do início da janela.':'— abaixo do início da janela.'}`,
    `${money(totalRevenue)} de faturamento líquido e ${money(totalMargin)} de margem na seleção atual.`,
    opportunities[0]?`Maior retração entre clientes rentáveis: ${opportunities[0].cliente} (${money(opportunities[0].variacao_2025)} em 2025 versus 2024).`: 'Sem oportunidades de retração na seleção atual.'
  ];
  return <div className="shell"><header className="topbar"><div className="brand"><div className="brand-mark">R</div><div><div className="eyebrow">Radar comercial</div><h1>Rentabilidade & carteira</h1><div className="sub">Painel interativo para gestores comerciais</div></div></div><div className="data-note">Base anonimizada · {D.meta.periodoInicial} a {D.meta.periodoFinal}<br/>Filtros aplicados no contexto de cada análise</div></header>
    <div className="filters"><div className="filter"><label>Business</label><select value={business} onChange={e=>{setBusiness(e.target.value);setCustomerFilter('Todos')}}><option>Todos</option>{D.meta.businesses.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter"><label>De</label><select value={from} onChange={e=>setFrom(e.target.value)}>{periods.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter"><label>Até</label><select value={to} onChange={e=>setTo(e.target.value)}>{periods.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter"><label>Filtro de carteira</label><select value={customerFilter} onChange={e=>setCustomerFilter(e.target.value)}>{groups.map(x=><option key={x}>{x}</option>)}</select></div><div className="range-buttons"><button className={from===D.meta.periodoInicial?'active':''} onClick={()=>{setFrom(D.meta.periodoInicial);setTo(D.meta.periodoFinal)}}>Todo período</button><button onClick={()=>setWindow(12)}>12 meses</button></div></div>
    <nav className="tabs">{tabs.map(([key,label])=><button key={key} className={`tab ${page===key?'active':''}`} onClick={()=>setPage(key)}>{label}</button>)}</nav>
    <div className="headline"><div><h2>{pageTitle[0]}</h2><p>{pageTitle[1]}</p></div><div className="sub">{business} · {from} → {to}</div></div>
    {page==='performance'&&<><div className="kpis"><Kpi label="Faturamento líquido" value={money(totalRevenue)} hint="Soma do período filtrado"/><Kpi label="Margem contribuição" value={money(totalMargin)} hint="Resultado após custos e deduções" tone={totalMargin>=0?'good':'bad'}/><Kpi label="Margem %" value={pct(totalRevenue?totalMargin/totalRevenue:0)} hint="Margem ponderada pelo faturamento" tone="good"/><Kpi label="Produtos em foco" value={topProducts.length} hint="Top produtos na seleção" tone="warn"/></div><div className="grid"><Card title="Vendas ao longo do tempo" caption="Faturamento líquido por período; acompanhe a escala comercial." className="span-8"><div className="chart"><ResponsiveContainer><AreaChart data={monthly}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#118DFF" stopOpacity=".35"/><stop offset="1" stopColor="#118DFF" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#E5E5E5"/><XAxis dataKey="periodo" minTickGap={28}/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>fullMoney(v)}/><Area name="Faturamento líquido" type="monotone" dataKey="faturamento" stroke="#118DFF" strokeWidth={3} fill="url(#area)" label={p=><EndLabel {...p} total={monthly.length}/>}/></AreaChart></ResponsiveContainer></div></Card><Card title="Evolução de margem" caption="A taxa é ponderada pelo faturamento mensal." className="span-4"><div className="chart"><ResponsiveContainer><LineChart data={monthly}><CartesianGrid strokeDasharray="3 3" stroke="#E5E5E5"/><XAxis dataKey="periodo" hide/><YAxis tickFormatter={x=>`${x.toFixed(0)}%`}/><Tooltip formatter={v=>`${v.toFixed(1)}%`}/><Line name="Margem %" type="monotone" dataKey={x=>x.margemPct*100} stroke="#1AAB40" strokeWidth={3} dot={false} label={p=><EndLabel {...p} total={monthly.length} kind="pct"/>}/></LineChart></ResponsiveContainer></div></Card><Card title="Vendas por produto" caption="Os dez produtos com maior faturamento no recorte." className="span-7"><div className="chart"><ResponsiveContainer><BarChart data={topProducts} layout="vertical" margin={{left:20,right:42}}><XAxis type="number" tickFormatter={compact}/><YAxis type="category" dataKey="produto" width={160} tick={{fontSize:11}}/><Tooltip formatter={v=>fullMoney(v)}/><Bar name="Faturamento" dataKey="faturamento" fill="#12239E" radius={[0,5,5,0]} label={{position:'right',formatter:compact,fill:'#605E5C',fontSize:10}}/></BarChart></ResponsiveContainer></div></Card><Card title="Insights de desempenho" className="span-5 insight"><ul>{insights.map(x=><li key={x}>{x}</li>)}</ul></Card></div></>}
    {page==='clientes'&&<><div className="kpis"><Kpi label="Clientes visíveis" value={compact(visibleCustomers.length)} hint="Conforme filtro de carteira"/><Kpi label="Clientes a recuperar" value={compact(visibleCustomers.filter(x=>x.grupo_cliente==='Recuperar margem').length)} hint="Escala com margem abaixo da referência" tone="warn"/><Kpi label="Oportunidades" value={compact(opportunities.length)} hint="Retração em 2025 versus 2024" tone="bad"/><Kpi label="Mix médio" value={(sum(visibleCustomers,'produtos_distintos')/Math.max(1,visibleCustomers.length)).toFixed(1)} hint="Produtos distintos por cliente" tone="good"/></div><div className="grid"><Card title="Valor por grupo de clientes" caption="Use os grupos para definir cobertura e tipo de ação." className="span-7"><div className="chart"><ResponsiveContainer><BarChart data={customerGroups}><XAxis dataKey="grupo_cliente" tick={{fontSize:11}}/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>fullMoney(v)}/><Bar name="Faturamento" dataKey="faturamento" fill="#118DFF" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Clientes rentáveis em retração" caption="Sinal para investigação; não prova perda definitiva." className="span-5"><Table rows={opportunities.slice(0,6)} cols={[{label:'Cliente',key:'cliente'},{label:'Variação 2025',num:true,render:r=>money(r.variacao_2025)},{label:'Mix',num:true,key:'produtos_distintos'}]}/></Card></div></>}
    {page==='churn'&&<><div className="kpis"><Kpi label="Ativos" value={compact(churn.find(x=>x.churn==='Ativo')?.clientes)} hint="Até 3 meses sem compra" tone="good"/><Kpi label="Em risco" value={compact(churn.find(x=>x.churn==='Em risco')?.clientes)} hint="Entre 4 e 12 meses" tone="warn"/><Kpi label="Churn observado" value={compact(churn.find(x=>x.churn==='Churn observado')?.clientes)} hint="Mais de 12 meses sem compra" tone="bad"/><Kpi label="Receita em risco" value={money((churn.find(x=>x.churn==='Em risco')||{}).faturamento)} hint="Faturamento histórico da faixa" tone="warn"/></div><div className="grid"><Card title="Carteira por status de churn" caption="A inatividade é observada pela última compra disponível." className="span-7"><div className="chart"><ResponsiveContainer><PieChart><Pie data={churn} dataKey="faturamento" nameKey="churn" outerRadius={100} label={({churn,payload})=>`${churn}: ${compact(payload.faturamento)}`}>{churn.map((x,i)=><Cell key={x.churn} fill={['#1AAB40','#D9B300','#D64554'][i]}/>)}</Pie><Tooltip formatter={v=>fullMoney(v)}/><Legend/></PieChart></ResponsiveContainer></div></Card><Card title="Ação recomendada" className="span-5 insight"><ul><li><strong>Ativo:</strong> proteger relacionamento e ampliar mix.</li><li><strong>Em risco:</strong> priorizar contato, proposta e revisão de condições.</li><li><strong>Churn observado:</strong> criar campanha de reativação antes de descartar a carteira.</li><li>A base tem variação de cobertura: valide o motivo da ausência de compra com o time comercial.</li></ul></Card></div></>}
    {page==='rfv'&&<><div className="kpis"><Kpi label="Campeões" value={compact(rfv.find(x=>x.grupo_rfv==='Campeões')?.clientes)} hint="Alta recência, frequência e valor" tone="good"/><Kpi label="Em risco de perda" value={compact(rfv.find(x=>x.grupo_rfv==='Em risco de perda')?.clientes)} hint="Valor relevante com recência baixa" tone="warn"/><Kpi label="Potencial a desenvolver" value={compact(rfv.find(x=>x.grupo_rfv==='Potencial a desenvolver')?.clientes)} hint="Valor alto e frequência a expandir"/><Kpi label="Faturamento dos campeões" value={money((rfv.find(x=>x.grupo_rfv==='Campeões')||{}).faturamento)} hint="Prioridade de retenção" tone="good"/></div><div className="grid"><Card title="Faturamento por grupo RFV" caption="RFV é relativo à carteira selecionada no conjunto de dados." className="span-8"><div className="chart"><ResponsiveContainer><BarChart data={rfv}><XAxis dataKey="grupo_rfv" tick={{fontSize:11}}/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>fullMoney(v)}/><Bar name="Faturamento" dataKey="faturamento" fill="#6B007B" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Leitura de RFV" className="span-4 insight"><ul><li><strong>Campeões:</strong> preservar valor e antecipar risco.</li><li><strong>Fiéis:</strong> elevar mix e margem.</li><li><strong>Em risco:</strong> reativar com ação dirigida.</li><li><strong>Potencial:</strong> aumentar frequência e cobertura.</li></ul></Card></div></>}
    {page==='segmentos'&&<><div className="kpis"><Kpi label="Clusters" value={clusters.length} hint="Agrupamento por perfil transacional"/><Kpi label="Estratégicos ativos" value={compact(visibleCustomers.filter(x=>x.grupo_cliente==='Estratégicos ativos').length)} hint="Escala, atividade e margem" tone="good"/><Kpi label="Inativos observados" value={compact(visibleCustomers.filter(x=>x.grupo_cliente==='Inativos observados').length)} hint="Prioridade de reativação" tone="bad"/><Kpi label="Margem a recuperar" value={money(sum(visibleCustomers.filter(x=>x.grupo_cliente==='Recuperar margem'),'margem'))} hint="Resultado do grupo" tone="warn"/></div><div className="grid"><Card title="Faturamento por cluster" caption="Clusters combinam valor, margem, recência, frequência e variedade de mix." className="span-6"><div className="chart"><ResponsiveContainer><BarChart data={clusters}><XAxis dataKey="cluster"/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>fullMoney(v)}/><Bar name="Faturamento" dataKey="faturamento" fill="#197278" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Ações por segmento" className="span-6"><Table rows={customerGroups} cols={[{label:'Grupo',key:'grupo_cliente',render:r=><span className="badge">{r.grupo_cliente}</span>},{label:'Clientes',num:true,render:r=>compact(r.clientes)},{label:'Faturamento',num:true,render:r=>money(r.faturamento)},{label:'Margem',num:true,render:r=>money(r.margem)}]}/></Card></div></>}
    <footer className="footer">Dados anonimizados e agregados localmente. Churn representa inatividade observada; RFV e clusters são instrumentos de priorização comercial, não diagnósticos causais.</footer>
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
