/* Dashboard local: estado, filtros, SVG charts, mapa e tabela. */
const DATA = window.FUEL_DASHBOARD_DATA;
const state = { page: 'overview', filters: { produto: 'GASOLINA COMUM', unidade: 'all', regiao: 'all', uf: 'all', inicio: DATA.meses[0], fim: DATA.meses.at(-1) } };
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const money = value => `${Number(value || 0).toLocaleString('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3})}`;
const pct = value => `${(Number(value || 0) * 100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
const month = value => String(value).slice(0, 7);

function addOptions(id, values, selected, allLabel = 'Todos') {
  const select = $(id); select.innerHTML = `<option value="all">${allLabel}</option>`;
  values.forEach(value => { const option = document.createElement('option'); option.value = value; option.textContent = value; select.appendChild(option); });
  select.value = selected;
}
function initFilters() {
  addOptions('f-produto', DATA.produtos.map(x => x.nome), state.filters.produto, 'Todos os produtos');
  addOptions('f-unidade', DATA.meta.unidades, state.filters.unidade, 'Todas as unidades');
  addOptions('f-regiao', DATA.regioes, state.filters.regiao, 'Todas as regiões');
  addOptions('f-uf', DATA.ufs.map(x => x.uf), state.filters.uf, 'Todas as UFs');
  addOptions('f-inicio', DATA.meses, state.filters.inicio, 'Início'); addOptions('f-fim', DATA.meses, state.filters.fim, 'Fim');
  ['produto','unidade','regiao','uf','inicio','fim'].forEach(key => $(`f-${key}`).addEventListener('change', () => { state.filters[key] = $(`f-${key}`).value; renderAll(); }));
  $('limpar').addEventListener('click', () => { state.filters = { produto: 'GASOLINA COMUM', unidade: 'all', regiao: 'all', uf: 'all', inicio: DATA.meses[0], fim: DATA.meses.at(-1) }; initFilters(); renderAll(); });
  $('exportar').addEventListener('click', exportCsv);
}
function filteredRows() {
  const f = state.filters; return DATA.mensal.filter(row => {
    const m = month(row.MES); return (f.produto === 'all' || row.PRODUTO === f.produto) && (f.unidade === 'all' || row['UNIDADE DE MEDIDA'] === f.unidade) && (f.regiao === 'all' || row['REGIÃO'] === f.regiao) && (f.uf === 'all' || row.UF === f.uf) && m >= f.inicio && m <= f.fim;
  });
}
function setStatus(rows) {
  const units = [...new Set(rows.map(x => x['UNIDADE DE MEDIDA']))];
  $('status').textContent = rows.length ? (units.length > 1 ? 'Atenção: o recorte mistura unidades; selecione um produto ou unidade para comparar preços.' : '') : 'Nenhum registro corresponde aos filtros atuais.';
}
function groupMean(rows, key) { const groups = new Map(); rows.forEach(row => { const k = row[key]; const item = groups.get(k) || { key:k, sum:0, n:0, registros:0, anomalias:0 }; item.sum += Number(row.preco) * Number(row.registros); item.n += Number(row.registros); item.registros += Number(row.registros); item.anomalias += Number(row.anomalias || 0); groups.set(k, item); }); return [...groups.values()].map(x => ({...x, value:x.n ? x.sum / x.n : 0})); }
function svgShell(w=800,h=300) { return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Gráfico interativo"><line class="axis" x1="55" y1="20" x2="55" y2="${h-35}"/><line class="axis" x1="55" y1="${h-35}" x2="${w-18}" y2="${h-35}"/>`; }
function lineChart(target, rows, seriesKey, onClick) {
  const bySeries = new Map(), months = [...new Set(rows.map(x => month(x.MES)))].sort(); rows.forEach(x => { const k=x[seriesKey]; if (!bySeries.has(k)) bySeries.set(k, new Map()); const cell=bySeries.get(k); const old=cell.get(month(x.MES)) || {sum:0,n:0}; old.sum += x.preco*x.registros; old.n += x.registros; cell.set(month(x.MES),old); });
  const series = [...bySeries.entries()].slice(0, 9), values=series.flatMap(([,m])=>[...m.values()].map(x=>x.n?x.sum/x.n:0)), min=Math.min(...values), max=Math.max(...values), w=800,h=300, x=i=>65+(i/Math.max(months.length-1,1))*700, y=v=>h-45-((v-min)/((max-min)||1))*210; let svg=svgShell(w,h);
  [0,.5,1].forEach(t=>{const yy= h-45-t*210; svg+=`<text x="8" y="${yy+4}">${money(min+t*(max-min))}</text>`;});
  series.forEach(([name,map],si)=>{const color=['#0f2b46','#3d6b96','#1c7a4f','#8a6a2f','#6b4c7a','#a32020','#56b4e9','#009e73','#cc79a7'][si]; const points=months.map((m,i)=>map.get(m)?.n ? `${x(i)},${y(map.get(m).sum/map.get(m).n)}` : '').filter(Boolean).join(' '); svg+=`<polyline class="line" stroke="${color}" points="${points}"/>`; const last=[...map.entries()].filter(([,v])=>v.n).at(-1); if(last){const i=months.indexOf(last[0]), val=last[1].sum/last[1].n; svg+=`<circle class="dot" fill="${color}" cx="${x(i)}" cy="${y(val)}" r="4" data-series="${esc(name)}"/><text x="${x(i)+7}" y="${y(val)+4}" fill="${color}">${esc(name)} ${money(val)}</text>`;}});
  months.filter((m,i)=>i===0||i===months.length-1||i%Math.max(1,Math.floor(months.length/5))===0).forEach(m=>{const i=months.indexOf(m); svg+=`<text x="${x(i)-18}" y="${h-12}">${m.slice(2)}</text>`;}); target.innerHTML=svg+'</svg>'; target.querySelectorAll('[data-series]').forEach(el=>el.addEventListener('click',()=>onClick?.(el.dataset.series))); }
function barChart(target, items, onClick) { const top=items.sort((a,b)=>b.value-a.value).slice(0,10), w=800, h=Math.max(260,top.length*30+40), max=Math.max(...top.map(x=>x.value),1), barW=690; let svg=svgShell(w,h); top.forEach((item,i)=>{const yy=28+i*28, width=item.value/max*barW; svg+=`<text x="2" y="${yy+13}">${esc(item.key)}</text><rect class="bar" x="110" y="${yy}" width="${width}" height="17" rx="2" fill="${i===0?'#8a6a2f':'#0f2b46'}" data-key="${esc(item.key)}"/><text x="${120+width}" y="${yy+13}">${money(item.value)}</text>`;}); target.innerHTML=svg+'</svg>'; target.querySelectorAll('[data-key]').forEach(el=>el.addEventListener('click',()=>onClick?.(el.dataset.key))); }
function kpis(rows) { const total=rows.reduce((s,x)=>s+x.preco*x.registros,0), n=rows.reduce((s,x)=>s+x.registros,0), vals=rows.map(x=>x.preco), avg=n?total/n:0, anomaly=rows.reduce((s,x)=>s+x.anomalias,0), spread=vals.length?Math.max(...vals)-Math.min(...vals):0; return [{label:'Preço médio',value:money(avg),sub:rows[0]?.['UNIDADE DE MEDIDA']||'unidade'}, {label:'Amplitude',value:money(spread),sub:'entre registros'}, {label:'Registros',value:n.toLocaleString('pt-BR'),sub:'observações agregadas'}, {label:'Anomalias',value:anomaly.toLocaleString('pt-BR'),sub:n?pct(anomaly/n):'sem base'}, {label:'Estados',value:new Set(rows.map(x=>x.UF)).size.toLocaleString('pt-BR'),sub:'com cobertura'}]; $('kpis').innerHTML=kpis(rows).map(x=>`<div class="card"><div class="label">${x.label}</div><div class="metric">${x.value}</div><div class="small">${x.sub}</div></div>`).join(''); }
function renderOverview(rows) { const f=state.filters; $('overview-title').textContent=`${f.produto==='all'?'Todos os produtos':f.produto} · ${f.inicio} a ${f.fim}`; $('coverage').textContent=`${rows.length.toLocaleString('pt-BR')} agregados`; kpis(rows); lineChart($('chart-trend'),rows,'REGIÃO',name=>{state.filters.regiao=name; $('f-regiao').value=name; renderAll();}); barChart($('chart-rank'),groupMean(rows,'UF'),name=>{state.filters.uf=name; $('f-uf').value=name; renderAll();}); const byRegion=groupMean(rows,'REGIÃO').sort((a,b)=>b.value-a.value), high=byRegion[0], low=byRegion.at(-1), an=groupMean(rows,'UF').sort((a,b)=>b.anomalias-b.anomalias)[0]; $('insights').innerHTML=`<div class="insight"><strong>${high?esc(high.key):'Sem dado'}</strong>${high?`maior preço médio no recorte: ${money(high.value)}.`:'Ajuste os filtros para encontrar uma diferença regional.'}</div><div class="insight"><strong>Amplitude regional</strong>${high&&low?`Entre ${esc(low.key)} e ${esc(high.key)}, a diferença média é ${money(high.value-low.value)}.`:'Sem comparação disponível.'}</div><div class="insight"><strong>Alerta de investigação</strong>${an&&an.anomalias?`${esc(an.key)} concentra ${an.anomalias.toLocaleString('pt-BR')} sinais de anomalia; valide a cobertura antes de agir.`:'Nenhuma anomalia no recorte.'}</div>`; }
function renderTemporal(rows) { const byState=groupMean(rows,'UF').sort((a,b)=>b.value-a.value).slice(0,8).map(x=>x.key); lineChart($('chart-states'),rows.filter(x=>byState.includes(x.UF)),'UF',name=>{state.filters.uf=name; $('f-uf').value=name; renderAll();}); }
function renderRegional(rows) { const byReg=groupMean(rows,'REGIÃO'), byUf=groupMean(rows,'UF'); barChart($('chart-regions'),byReg.map(x=>({...x,key:x.key,value:Math.max(...byUf.filter(y=>DATA.ufs.find(u=>u.uf===y.key)?.regiao===x.key).map(y=>y.value),0)-Math.min(...byUf.filter(y=>DATA.ufs.find(u=>u.uf===y.key)?.regiao===x.key).map(y=>y.value),0)}))); $('regional-summary').innerHTML=byReg.map(r=>{const u=byUf.filter(x=>DATA.ufs.find(y=>y.uf===x.key)?.regiao===r.key).sort((a,b)=>b.value-a.value);return `<div class="summary-row"><b>${esc(r.key)}</b><span>maior ${esc(u[0]?.key||'—')} · ${money(u[0]?.value||0)}</span><span>menor ${esc(u.at(-1)?.key||'—')} · ${money(u.at(-1)?.value||0)}</span></div>`}).join(''); $('regional-table').innerHTML=table(byUf.sort((a,b)=>b.value-a.value).map(x=>{const u=DATA.ufs.find(y=>y.uf===x.key);return {regiao:u?.regiao,uf:x.key,preco:x.value,registros:x.registros,anomalias:x.anomalias};}),['regiao','uf','preco','registros','anomalias']); }
function table(rows, cols) { const labels={regiao:'Região',uf:'UF',preco:'Preço médio',registros:'Registros',anomalias:'Anomalias',mes:'Mês',produto:'Produto',unidade:'Unidade'}; return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${labels[c]||c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,180).map(r=>`<tr>${cols.map(c=>`<td>${esc(c==='preco'?money(r[c]):r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function renderDetail(rows) { const detail=rows.sort((a,b)=>b.preco-a.preco).map(x=>({mes:month(x.MES),produto:x.PRODUTO,unidade:x['UNIDADE DE MEDIDA'],regiao:x['REGIÃO'],uf:x.UF,preco:x.preco,registros:x.registros,anomalias:x.anomalias})); $('detail-meta').textContent=`${detail.length.toLocaleString('pt-BR')} linhas agregadas · exibindo até 180 linhas ordenadas por preço`; $('detail-table').innerHTML=table(detail,['mes','produto','unidade','regiao','uf','preco','registros','anomalias']); }
function project([lon,lat]) { return [((lon+75)/42)*760+20, ((6-lat)/42)*500+10]; }
function pathFor(geometry) { const polygon=ring=>ring.map((p,i)=>`${i?'L':'M'}${project(p).map(x=>x.toFixed(1)).join(',')}`).join(' ')+'Z'; if(geometry.type==='Polygon')return geometry.coordinates.map(polygon).join(' '); return geometry.coordinates.map(poly=>poly.map(polygon).join(' ')).join(' '); }
function renderMap(rows) { const byUf=groupMean(rows,'UF'), vals=byUf.map(x=>x.value), min=Math.min(...vals), max=Math.max(...vals), by=Object.fromEntries(byUf.map(x=>[x.key,x])); const geo=DATA.geojson; $('map').innerHTML=`<svg viewBox="0 0 800 530" aria-label="Mapa do Brasil por Unidade da Federação">${geo.features.map(feature=>{const uf=DATA.ufs.find(x=>x.codigo===feature.properties.codarea)?.uf, item=by[uf], t=item?(item.value-min)/((max-min)||1):null, color=t===null?'#d6dce4':`rgb(${Math.round(255-140*t)},${Math.round(245-115*t)},${Math.round(235-25*t)})`; return `<path class="uf-shape" d="${pathFor(feature.geometry)}" fill="${color}" data-uf="${uf||''}"><title>${uf||'UF'} · ${item?money(item.value):'Sem dado'} · ${item?.registros||0} registros</title></path>`}).join('')}</svg>`; $('map').querySelectorAll('[data-uf]').forEach(el=>el.addEventListener('click',()=>{state.filters.uf=el.dataset.uf;$('f-uf').value=el.dataset.uf;renderAll();})); $('legend').innerHTML=`<span>Menor</span><span class="legend-scale"></span><span>Maior</span><span>${money(min)}–${money(max)} ${rows[0]?.['UNIDADE DE MEDIDA']||''}</span>`; }
function exportCsv() { const rows=filteredRows(), headers=['MES','PRODUTO','UNIDADE DE MEDIDA','REGIÃO','UF','preco','registros','postos_medios','anomalias']; const csv=[headers.join(';'),...rows.map(row=>headers.map(h=>`"${String(row[h]??'').replaceAll('"','""')}"`).join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); a.download='precos-combustiveis-recorte.csv'; a.click(); URL.revokeObjectURL(a.href); }
function renderAll() { const rows=filteredRows(); setStatus(rows); const page=state.page; if(page==='overview')renderOverview(rows); if(page==='temporal')renderTemporal(rows); if(page==='regional')renderRegional(rows); if(page==='mapa')renderMap(rows); if(page==='detail')renderDetail(rows); }
function initPages() { document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{state.page=btn.dataset.page;document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${state.page}`));renderAll();})); }
function start() { $('periodo').textContent=`${DATA.meta.inicio} — ${DATA.meta.fim}`; initFilters(); initPages(); renderAll(); }
document.addEventListener('DOMContentLoaded', start);
